import type { Metadata } from "next";
import localFont from 'next/font/local'
import { IBM_Plex_Mono } from 'next/font/google'
import "./globals.css";

const yeezy = localFont({
  src: '../public/yeezy_tstar-bold-webfont.ttf'
})

const inter = IBM_Plex_Mono({ weight: ['400'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
